### ISSUE TITLE
Snapshot and submit RFP for Layerzero token airdrop (by May 31st)

### ISSUE THREAD

**Issue by telos-justin** [telosnetwork/TCD-Portal#18]
https://commonwealth.im/layerzero/discussion/17246-protocol-rfp

**Comment by rozzaswap** [comment]
Proposal document: 

https://docs.google.com/document/d/1vr697fuz86kTwtwePqh41OHPJ-7hL8JNa5x5itJsWo0/edit?usp=sharing

Snapshot wallets: 

https://drive.google.com/file/d/1Hyt2kXUYFalLhFaRqJuDCtQLEYdFl7k7/view?usp=sharing
